### ISSUE TITLE
Scale without UI/HUD acting strange?

### ISSUE THREAD

**Issue by AwesomeTrinket** [00due/RMMZ-ScreenTransform#1]
Hello,

I've been using this plugin for... about a day now? My main issue is that, when I try to use the "Scale/Stretch" option, while EXCLUDING the use of UI/HUD, it starts to zoom in for a frame or two, and then just... forces the camera to focus on the lower right corner? When I use the Full Screen version that INCLUDES UI/HUD, it works as planned. That said, my game relies heavily on Pictures, so being able to zoom in while affecting Pictures and NOT the UI is really important to me.

Please feel free to tell me if I'm doing anything wrong in setting up the Zoom-in plugin. Attached is how I have it set up WITHOUT UI/HUD that makes it break. Video showcases what happens when I execute it. This is on a blank project with literally only this plugin.

![image](https://github.com/user-attachments/assets/4275f511-63c8-4557-9ad6-a852ef3c8e39)

https://github.com/user-attachments/assets/4a1b531e-a5b8-4275-8a07-38e86fd4e183

**Comment by 00due** [comment]
I guess that has something to do with that layer having a different resolution or a pivot point in another place. I'll look into it tomorrow. 

In the meantime, you could try to disable "set pivot" as a workaround. I'm not sure if this'll work. I'll look for a real fix later.

**Comment by 00due** [comment]
Sorry for taking so long with fixing this. Fixed now with [#b63b3ee](https://github.com/00due/RMMZ-ScreenTransform/commit/b63b3eece600acd14b8e7b61542b4902ce51d578) but take a look at the plugin parameters.
